[package]
name = "nbishop-net"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.57"
argh = "0.1.7"
camino = "1.0.9"
command-run = "1.1.1"
comrak = "0.12.1"
fs-err = "2.7.0"
serde = { version = "1.0.137", features = ["derive"] }
tera = "1.15.0"
time = "0.3.9"
walkdir = "2.3.2"
