on:
  push:
    branches:
      - main

name: Publish

jobs:
  check:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y lld
      - uses: actions/checkout@v4
        with:
          # This does a full clone instead of a shallow clone, which is
          # needed for the "last-modified" code to work.
          fetch-depth: 0
      - uses: Swatinem/rust-cache@v2
      - run: cargo run --release -- --publish
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
